paths:
  hero_cards_suits: '../images_templates/hero_cards_suits/'
  hero_cards_numbers: '../images_templates/hero_cards_numbers/'
  table_cards_numbers: '../images_templates/table_cards_numbers/'
  table_cards_suits: '../images_templates/table_cards_suits/'
  pot_numbers: '../images_templates/pot_numbers/'
  pot_image: '../images_templates/pot/pot.png'
  dealer_button: '../images_templates/dealer_button/button.png'
  empty_seat: '../images_templates/empty_seat/empty_seat.png'
  sitting_out: '../images_templates/sitting_out/so.png'


table_size:
  width: 1090
  height: 900

info_box_size:
  width: 470
  height: 500

hero_step_define:
  x_0: 511
  y_0: 605
  x_1: 528
  y_1: 644
  lower_gray_color: [0, 5, 50]
  upper_gray_color: [179, 10, 255]
  min_white_pixels: 400


hero_cards:
  x_0: 478
  y_0: 535
  x_1: 616
  y_1: 592
  # x coordinate where the card ends
  separator_1: 67
  separator_2: 137

table_cards:
  x_0: 364
  y_0: 319
  x_1: 730
  y_1: 414
  # x coordinate where the card ends
  separator_1: 72
  separator_2: 144
  separator_3: 218
  separator_4: 290
  separator_5: 363

pot:
  # in what area looking for pot
  x_0: 472
  y_0: 279
  x_1: 636
  y_1: 328
  # the maximum width and height over which
  # the sum of the bet can be placed
  width: 100
  height: 20
  pot_template_width: 33

player_center_coordinates:
  # the first player is the hero and then clockwise
  # coordinates are stored in [x, y] format
  1: [469, 598]
  2: [208,463]
  3: [237,278]
  4: [620,200]
  5: [857, 274]
  6: [867, 486]

players_coordinates:
  # coordinates are stored in [x_0, y_0, x_1, y_1] format
  1: [437,592,655,661]
  2: [21,450, 245,525]
  3: [49,214, 275,285]
  4: [437, 139, 659, 213]
  5: [814, 214, 1040,288]
  6: [850, 449, 1075, 524]

players_bet:
  # coordinates are stored in [x_0, y_0, x_1, y_1] format
  2: [279, 457, 379, 480]
  3: [292, 296, 392, 318]
  4: [600, 222, 700, 246]
  5: [688, 270, 788, 292]
  6: [717, 457, 817, 480]