paths:
  hero_cards_suits: '../images_templates/hero_cards_suits/'
  hero_cards_numbers: '../images_templates/hero_cards_numbers/'
  table_cards_numbers: '../images_templates/table_cards_numbers/'
  table_cards_suits: '../images_templates/table_cards_suits/'
  pot_numbers: '../images_templates/pot_numbers/'
  pot_image: '../images_templates/pot/pot.png'
  dealer_button: '../images_templates/dealer_button/button.png'


table_size:
  table_width: 1090
  table_height: 900

hero_step_define:
  x_0: 511
  y_0: 605
  x_1: 528
  y_1: 644
  lower_gray_color: [0, 5, 50]
  upper_gray_color: [179, 10, 255]
  min_white_pixels: 400


hero_cards:
  x_0: 478
  y_0: 535
  x_1: 616
  y_1: 592
  separator_1: 67
  separator_2: 137

table_cards:
  x_0: 364
  y_0: 319
  x_1: 730
  y_1: 414
  separator_1: 72
  separator_2: 144
  separator_3: 218
  separator_4: 290
  separator_5: 363

pot:
  # in what area looking for pot
  x_0: 472
  y_0: 279
  x_1: 636
  y_1: 328
  # the maximum width and height over which
  # the sum of the bet can be placed
  width: 100
  height: 20
  pot_template_width: 33

player_position_coordinates:
  # the first player is the hero and then clockwise
  # coordinates are stored in [x, y] format
  1: [469, 598]
  2: [208,463]
  3: [237,278]
  4: [620,200]
  5: [857, 274]
  6: [867, 486]